### ISSUE TITLE
Take context.Context as part of each method's parameters 

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/oxide.go#122]
# Overview

We would like our users to have the ability to pass a `context.Context` to each of our methods in this manner:

```go
	params := oxide.ProjectCreateParams{...}
	ctx := context.Background()
	resp, _ := client.ProjectCreate(ctx, params)
```

# Implementation details

To make this change we'll need the following:

1. Within the `oxide/lib.go` file, the `buildRequest()` function will need to be modified to take a `context.Context` as the first parameter. Additionally, instead of creating the request with `http.NewRequest()`, we'll want to use `http.NewRequestWithContext()`.
2. Before generating any code, the templates will need to be updated so the generated methods take a `context.Context` as a parameter. Inside the `internal/generate/templates/` directory, we'll be modifying the `resptype_method.tpl`, `resptype_body_method.tpl`, `no_resptype_method.tpl`, `no_resptype_body_method.tpl`, and `listall_method.tpl` files. In each file the following change should be made:
```console
--- a/internal/generate/templates/no_resptype_body_method.tpl
+++ b/internal/generate/templates/no_resptype_body_method.tpl
@@ -1,4 +1,4 @@
-{{template "description" .}}func (c *Client) {{.FunctionName}}({{.ParamsString}}) error { {{if .HasParams}}
+{{template "description" .}}func (c *Client) {{.FunctionName}}(ctx context.Context, {{.ParamsString}}) error { {{if .HasParams}}
     if err := params.Validate(); err != nil {
                return err
        }{{end}}{{if .IsAppJSON}}
@@ -11,6 +11,7 @@
 
     // Create the request
     req, err := buildRequest(
+        ctx,
         b, 
```
  The `listall_method.tpl` is a little bit different. Here we will be making the following change:
```console
--- a/internal/generate/templates/listall_method.tpl
+++ b/internal/generate/templates/listall_method.tpl
@@ -1,4 +1,4 @@
-{{template "description" .}}func (c *Client) {{.FunctionName}}({{.ParamsString}}) (*{{.ResponseType}}, error) { {{if .HasParams}}
+{{template "description" .}}func (c *Client) {{.FunctionName}}(ctx context.Context, {{.ParamsString}}) (*{{.ResponseType}}, error) { {{if .HasParams}}
        if err := params.Validate(); err != nil {
                return nil, err
        }{{end}}
@@ -6,7 +6,7 @@
@@ -6,7 +6,7 @@
        params.PageToken = ""
        params.Limit = 100
        for {
-               page, err := c.{{.WrappedFunction}}(params)
+               page, err := c.{{.WrappedFunction}}(ctx, params)
```
3. Once all templates have been modified, all that needs to be done is to run `make generate` (there will be some warnings which can be safely ignored).
4. Some tests will need to be updated. For the `Test_generatePaths` test, all that needs to be done is: Run the test and have it fail, then copy the new output from `internal/generate/test_utils/paths_output` to `internal/generate/test_utils/paths_output_expected`.  The `Test_buildRequest` test in `oxide/lib_test.go` will also need to be updated to pass a `context.Context`.
5. Update the example in the README file

**Comment by sudomateo** [comment]
Hello! I'd like to work on this. I just wanted to clarify what timeout this issue is referencing.

Is it just the `Timeout` on the `http.Client`?

https://github.com/oxidecomputer/oxide.go/blob/2bfa4c07c2c0b5d3237253e4982a2ada68627c4c/oxide/lib.go#L68

The lower-level timeouts on the `Transport`?

https://github.com/oxidecomputer/oxide.go/blob/2bfa4c07c2c0b5d3237253e4982a2ada68627c4c/oxide/lib.go#L60

Or something else?

**Comment by karencfv** [comment]
Awesome! I'll work on writing a proper issue tomorrow instead of my crappy "just-the-title-it'll-be-alright" approach.

**Comment by sudomateo** [comment]
> Awesome! I'll work on writing a proper issue tomorrow instead of my crappy "just-the-title-it'll-be-alright" approach.

No worries! Just ping me when you get around to populating the issue description. Appreciate it!

**Comment by karencfv** [comment]
Heya @sudomateo! sorry for the wait. 

As I was looking at the code I realised there are some big changes I want to make to `NewClient()` itself, so I'm modifying the scope of this issue. What we really want our customers to have as part of this issue, is the ability to pass a `context.Context` within each of the methods. 

I've updated this issue to reflect the necessary changes. Please let me know if something isn't clear!

Just a heads up that this issue in particular is something that we want to have as part of our next release. I totally understand if you're very busy and don't have time to work on this, please let me know if this is the case :)

**Comment by sudomateo** [comment]
Thank you for the awesome writeup @karencfv! I submitted #144 to resolve this issue.
