### ISSUE TITLE
userAgent shouldn't be required for creating new client

### ISSUE THREAD

**Issue by halkyon** [oxidecomputer/oxide.go#165]
It may be more useful to specify the user agent optionally instead of requiring it for creating the SDK client.

Example:

```go
client, err := oxide.NewClient("abc1234token", "https://host-to-oxide")
if err != nil {
  return err
}

client.WithUserAgent("my cool agent v1.0")

// ... do the actual work
```

If I don't specify the user agent, it possibly could autogenerate it from the current version of the SDK, e.g. "Oxide Go SDK v1.3". If other code like Terraform provider is using it, it could even double it up, e.g. "Oxide Terraform v1.0, Oxide Go SDK v1.1".

**Comment by karencfv** [comment]
Thanks @halkyon :bowing_woman:  This is a really nice idea!
