### ISSUE TITLE
allow a way of creating client from known environment variables

### ISSUE THREAD

**Issue by halkyon** [oxidecomputer/oxide.go#166]
At the moment you have to specify token and host when creating the client. Since it seems `OXIDE_HOST` and `OXIDE_TOKEN` was already used for the Terraform provider and Oxide CLI, you could possibly have something like:

```
client, err := oxide.NewClientFromEnvironmentCredentials()
if err != nil {
  panic(err)
}
```

**Comment by karencfv** [comment]
Fixed by #180
