### ISSUE TITLE
mark fields in documentation which are required in parameters

### ISSUE THREAD

**Issue by halkyon** [oxidecomputer/oxide.go#167]
Would be good to see in Go docs if a field is required in parameter structs, it also helps when writing the code using an IDE like VS Code. The other thing is knowing which fields are required or optional depending on the type given, e.g. disk attachment vs create when creating an instance.

**Comment by karencfv** [comment]
Thanks for taking the time to write this :) Linking a somewhat related issue https://github.com/oxidecomputer/oxide.go/issues/157
